name: clustermatch
channels:
- defaults
dependencies:
- tabulate=0.8
- ipython=6.2
- joblib=0.12
- numpy=1.13
- pandas=0.21
- python=3.6
- scikit-learn=0.19
- scipy=1.0.0
- xlrd=1.1
- xlwt=1.3
- openpyxl=2.4
